### ISSUE TITLE
Что такое Cons и Vol? Непонятно

### ISSUE THREAD

**Issue by coursar** [jafarsirojov/fuelCon#5]
https://github.com/jafarsirojov/fuelCon/blob/6bc3d6fcd385fd69ace6c3144c2162840876eb1c/main.go#L11

**Comment by jafarsirojov** [comment]
@coursar, Consumption-расход, Volume-объем, короткий вид

**Comment by coursar** [comment]
Это не надо писать в комментарии - это надо писать в коде, без короткого вида. Не экономьте на именах переменных
